// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeS-8DJlxgZ92Cva33Ie_ncPdfJIU777A',
    appId: '1:924814360113:web:923912747d6a276f10df10',
    messagingSenderId: '924814360113',
    projectId: 'cs3541-lab5aw',
    authDomain: 'cs3541-lab5aw.firebaseapp.com',
    storageBucket: 'cs3541-lab5aw.firebasestorage.app',
    measurementId: 'G-S7Q0VW8PPN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWVUPAIc7cb7FUt176ngLF4IYZh_XlRxk',
    appId: '1:924814360113:android:7a5de68418a9777110df10',
    messagingSenderId: '924814360113',
    projectId: 'cs3541-lab5aw',
    storageBucket: 'cs3541-lab5aw.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDkDhGg5YAL5iDmnYx8fl8-kH_F1z4tSIA',
    appId: '1:924814360113:ios:5fcd626eafc0704310df10',
    messagingSenderId: '924814360113',
    projectId: 'cs3541-lab5aw',
    storageBucket: 'cs3541-lab5aw.firebasestorage.app',
    iosBundleId: 'com.example.flutterTipcalc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDkDhGg5YAL5iDmnYx8fl8-kH_F1z4tSIA',
    appId: '1:924814360113:ios:5fcd626eafc0704310df10',
    messagingSenderId: '924814360113',
    projectId: 'cs3541-lab5aw',
    storageBucket: 'cs3541-lab5aw.firebasestorage.app',
    iosBundleId: 'com.example.flutterTipcalc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeS-8DJlxgZ92Cva33Ie_ncPdfJIU777A',
    appId: '1:924814360113:web:83aa2014a7ed20ef10df10',
    messagingSenderId: '924814360113',
    projectId: 'cs3541-lab5aw',
    authDomain: 'cs3541-lab5aw.firebaseapp.com',
    storageBucket: 'cs3541-lab5aw.firebasestorage.app',
    measurementId: 'G-PBRWBK8T2Z',
  );
}
