import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'tip_view.dart';
import 'firebase_options.dart'; // generated by flutterfire configure

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Firestore Tip Calculator - MVP',
      theme: ThemeData(
        colorScheme: ColorScheme.fromSeed(seedColor: Colors.teal),
        useMaterial3: true,
      ),
      initialRoute: '/',
      routes: {
        '/': (context) =>
            const TipCalculatorPage(title: 'Firebase Tip Calculator'),
        '/history': (context) =>
            const HistoryPage(title: 'Tip History', history: [],), 
      },
    );
  }
}

